Update class-friends.php
akirk/friends pull request #328
Opened 2024-06-16 18:18 UTC by apermo

Changed: Replaced role name capability with manage_options
Added: PHPdoc

This fixes #327

2024-06-16 18:32 UTC, akirk requested changes
Thanks! I just think you have a typo.

2024-06-16 18:32 UTC, akirk commented on includes/class-friends.php
> +		return self::is_main_user() || current_user_can( 'edit_options' );
I think it should be this!
```suggestion
		return self::is_main_user() || current_user_can( 'manage_options' );
```

2024-06-17 09:34 UTC, apermo commented
> Thanks! I just think you have a typo.

Absolutely a typo. You’re right.

2024-06-18 09:30 UTC, akirk approved these changes
Thank you!

2024-06-19 13:49 UTC, merged